### ISSUE TITLE
fluxctl sync ERROR

### ISSUE THREAD

**Issue by liminghua999** [youngercloud/flux-get-start-easy#1]
`你好，这个项目测试还能使用吗？
我安装你的介绍，简单操作了下，但是无法通过，在fluxctl sync 报错：
1： git clone https://github.com/fluxcd/flux.git
2:  修改 flux/deploy/flux-deployment.yaml的--git-url 为我clone你的youngercloud/flux-get-start-easy项目
3：然后fluxctl identity --k8s-fwd-ns xx 获取ssh key并添加到我clone的项目中，给与读写权限
4：就是该fluxtl sync  --k8s-fwd-ns xx 
此时就报错：
[root@m-etc-1 flux]# fluxctl sync --k8s-fwd-ns flux
Error: git repository ssh://git@github.com/xxx/flux-get-start-easy.git is not ready to sync

Full error message: git clone --mirror: running git command: git [clone --mirror git@github.com:xxxx/flux-get-start-easy.git /tmp/flux-gitclone984723138]: context deadline exceeded
Run 'fluxctl sync --help' for usage.
麻烦给与一些帮助 谢谢
`

**Comment by youngercloud** [comment]
真是抱歉，现在才看见。因为我没有跟进这个project一年多了，目前也不知道这个项目怎么样了。个人建议还是去Github提个Issue吧。

開啟 週五, 11月 27, 2020 在 6:17 下午, liminghua999 <notifications@github.com> 寫道：
